add CloudProvider field for customer statement
claranet/cloudhealth-sdk-go pull request #3
Opened 2020-09-17 15:04 UTC by mboret

2020-09-17 15:07 UTC, Shr3ps approved these changes

2020-09-17 20:15 UTC, Issif commented
The SDK is still alive 👍

2020-09-19 19:41 UTC, Issif requested changes

2020-09-19 19:41 UTC, Issif commented on customer_statements_test.go
> +	                CloudProvider: "AWS",
```suggestion
			CloudProvider: "AWS",
```

2020-09-19 19:41 UTC, Issif commented on customer_statements_test.go
> +	                CloudProvider: "AWS",
```suggestion
			CloudProvider: "AWS",
```

2020-09-25 14:29 UTC, pdecat requested changes
Replace spaces by tabs as suggested by @Issif and you're good to go :)

2020-10-06 16:32 UTC, mboret commented
@pdecat Done

2020-10-07 08:45 UTC, pdecat approved these changes
LGTM!

2020-10-19 07:47 UTC, mboret commented
@Shr3ps merge please...

2020-10-19 07:58 UTC, xp-1000 approved these changes

2020-10-19 08:44 UTC, merged